## 习题1.1 ##

In [23]:
import numpy as np

In [9]:
# 19
x = np.array([-3.1, -3.01, -3.001, -2.999, -2.99, -2.9])
y = (x ** 2 - 9) / (x + 3)
y

array([-6.1  , -6.01 , -6.001, -5.999, -5.99 , -5.9  ])

In [14]:
# 20
sqrt_2 = 2 ** (1/2)
print(sqrt_2)
x = np.array([1.4, 1.41, 1.414, 1.4142, 1.4142])
y = (x ** 2 - 2) / (x - sqrt_2)
y

1.4142135623730951


array([2.81421356, 2.82421356, 2.82821356, 2.82841356, 2.82841356])

In [16]:
# 21
x = np.array([-5.9, -5.99, -5.999, -5.9999])
y = (x + 6) / (x**2 + 4*x - 12)
y

array([-0.12658228, -0.12515645, -0.12501563, -0.12500156])

In [17]:
# 22
x = np.array([2.9, 2.99, 2.999, 3.001, 3.01, 3.1])
y = (x**2 - 2*x - 3) / (x**2 - 4*x + 3)
y

array([2.05263158, 2.00502513, 2.00050025, 1.99950025, 1.99502488,
       1.95238095])

In [25]:
# 23
theta = np.array([-.1, -.01, -.001, -.0001, .0001, .001, .01, .1])
y = np.sin(theta) / theta
y

array([0.99833417, 0.99998333, 0.99999983, 1.        , 1.        ,
       0.99999983, 0.99998333, 0.99833417])

In [28]:
# 24
t = np.array([-.1, -.01, -.001, -.0001, .0001, .001, .01, .1])
y = (1 - np.cos(t)) / (t**2)
y

array([0.49958347, 0.49999583, 0.49999996, 0.5       , 0.5       ,
       0.49999996, 0.49999583, 0.49958347])

In [33]:
# 25
x = np.array([0.9, 0.99, 0.999, 0.9999, 1.0001, 1.001, 1.01, 1.1])
y = x**(1/(1-x))
y

array([0.34867844, 0.36603234, 0.36769542, 0.36786105, 0.36789783,
       0.3680633 , 0.36971121, 0.38554329])

In [36]:
# 26
x = np.array([-.1, -.01, -.001, -.0001, -.00001, .00001, .0001, .001, .01, .1])
y = (3**x - 1)/x
y

array([1.0404154 , 1.09259958, 1.09800904, 1.09855194, 1.09860625,
       1.09861832, 1.09867264, 1.09921598, 1.10466919, 1.16123174])

In [38]:
# 43
x = np.array([-.1, -.01, -.001, -.0001])
y = x * np.sin(1/x)
print(y)
x = np.array([.1, .01, .001, .0001])
y = x * np.sin(1/x)
print(y)

[-5.44021111e-02 -5.06365641e-03  8.26879541e-04 -3.05614389e-05]
[-5.44021111e-02 -5.06365641e-03  8.26879541e-04 -3.05614389e-05]


In [39]:
# 44
x = np.array([-.1, -.01, -.001, -.0001])
y = np.sin(1/x)
print(y)
x = np.array([.1, .01, .001, .0001])
y = np.sin(1/x)
print(y)

[ 0.54402111  0.50636564 -0.82687954  0.30561439]
[-0.54402111 -0.50636564  0.82687954 -0.30561439]


In [40]:
# 45
x = np.array([-.1, -.01, -.001, -.0001])
y = (10**x - 1)/x
print(y)
x = np.array([.1, .01, .001, .0001])
y = (10**x - 1)/x
print(y)

[2.05671765 2.2762779  2.29993618 2.30232002]
[2.58925412 2.32929923 2.30523808 2.30285021]


In [41]:
# 46
x = np.array([-.1, -.01, -.001, -.0001])
y = x * np.sin(np.log(np.abs(x)))
print(y)
x = np.array([.1, .01, .001, .0001])
y = x * np.sin(np.log(np.abs(x)))
print(y)

[ 7.43980337e-02 -9.94257569e-03  5.84748482e-04  2.12797932e-05]
[-7.43980337e-02  9.94257569e-03 -5.84748482e-04 -2.12797932e-05]


In [ ]:
# 47
